#!/bin/bash

printf "\n[TESTING GRID FILES]\n"

for f in Sudokus/gridTest/*
do
    printf "\nFILE: $f\n"
    ./KillerSudokuChecker $f
done

printf "\n[TESTING SOLUTION FILES]\n"

for f in Sudokus/solTest/*
do
    printf "\nFILE: $f\n"
    ./KillerSudokuChecker Sudokus/2by2example.ks $f
done

printf "\n"
